name: Build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '25'
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v5
      - run: ./gradlew check build outJar :buildSrc:check publishToMavenLocal --stacktrace
      - uses: FabricMCBot/publish-checkstyle-report@v3
        if: ${{ failure() }}
        with:
          reports: |
            **/build/reports/checkstyle/*.xml
      - uses: actions/upload-artifact@v7
        with:
          name: Artifacts ${{ matrix.java }}
          path: |
            build/libs/
            ./*/build/libs/
            build/publishMods/
      - uses: actions/upload-artifact@v7
        with:
          name: Maven Local ${{ matrix.java }}
          path: ~/.m2/repository/net/fabricmc/
      - uses: actions/upload-artifact@v7
        with:
          name: Artifacts ${{ matrix.java }}
          archive: false
          path: |
            build/out/
